
.macro release_dbus			; 2 cycles (let others use the data bus)
	out DDRD, zero			;
	out PORTD, zero			;
.endmacro


.macro occupy_dbus			; 3 cycles (get control of the data bus)
	out PORTD, zero			;
	ser tmp4				;
	out DDRD, tmp4			;
.endmacro


.macro clr_cur				; toggle cursor if visible
	in tmp2, fcnt			;
	sbrc tmp2, 7			;
	call ct_toggle			;
.endmacro


.macro set_cur				; reset cursor state
	out fcnt, zero			;
	call ct_toggle			;
.endmacro


.macro nop_x4				; 4 cycles
	nop						;
	nop						;
	nop						;
	nop						;
.endmacro


.macro nop_x2				; 2 cycles
	nop						;
	nop						;
.endmacro


.macro get_line_data			; 512 cycles
	inc isr_temp2				;
	out PORTC, isr_temp2		;
	inc isr_temp2				;
	out PORTC, isr_temp2		;
	inc isr_temp2				;
	out PORTC, isr_temp2		;
	inc isr_temp2				;
	out PORTC, isr_temp2		;
	inc isr_temp2				;
	out PORTC, isr_temp2		;
	inc isr_temp2				;
	out PORTC, isr_temp2		;
	inc isr_temp2				;
	out PORTC, isr_temp2		;
	inc isr_temp2				;
	out PORTC, isr_temp2		;
	inc isr_temp2				;
	out PORTC, isr_temp2		;
	inc isr_temp2				;
	out PORTC, isr_temp2		;
	inc isr_temp2				;
	out PORTC, isr_temp2		;
	inc isr_temp2				;
	out PORTC, isr_temp2		;
	inc isr_temp2				;
	out PORTC, isr_temp2		;
	inc isr_temp2				;
	out PORTC, isr_temp2		;
	inc isr_temp2				;
	out PORTC, isr_temp2		;
	inc isr_temp2				;
	out PORTC, isr_temp2		;
	inc isr_temp2				;
	out PORTC, isr_temp2		;
	inc isr_temp2				;
	out PORTC, isr_temp2		;
	inc isr_temp2				;
	out PORTC, isr_temp2		;
	inc isr_temp2				;
	out PORTC, isr_temp2		;
	inc isr_temp2				;
	out PORTC, isr_temp2		;
	inc isr_temp2				;
	out PORTC, isr_temp2		;
	inc isr_temp2				;
	out PORTC, isr_temp2		;
	inc isr_temp2				;
	out PORTC, isr_temp2		;
	inc isr_temp2				;
	out PORTC, isr_temp2		;
	inc isr_temp2				;
	out PORTC, isr_temp2		;
	inc isr_temp2				;
	out PORTC, isr_temp2		;
	inc isr_temp2				;
	out PORTC, isr_temp2		;
	inc isr_temp2				;
	out PORTC, isr_temp2		;
	inc isr_temp2				;
	out PORTC, isr_temp2		;
	inc isr_temp2				;
	out PORTC, isr_temp2		;
	inc isr_temp2				;
	out PORTC, isr_temp2		;
	inc isr_temp2				;
	out PORTC, isr_temp2		;
	inc isr_temp2				;
	out PORTC, isr_temp2		;
	inc isr_temp2				;
	out PORTC, isr_temp2		;
	inc isr_temp2				;
	out PORTC, isr_temp2		;
	inc isr_temp2				;
	out PORTC, isr_temp2		;
	inc isr_temp2				;
	out PORTC, isr_temp2		;
	inc isr_temp2				;
	out PORTC, isr_temp2		;
	inc isr_temp2				;
	out PORTC, isr_temp2		;
	inc isr_temp2				;
	out PORTC, isr_temp2		;
	inc isr_temp2				;
	out PORTC, isr_temp2		;
	inc isr_temp2				;
	out PORTC, isr_temp2		;
	inc isr_temp2				;
	out PORTC, isr_temp2		;
	inc isr_temp2				;
	out PORTC, isr_temp2		;
	inc isr_temp2				;
	out PORTC, isr_temp2		;
	inc isr_temp2				;
	out PORTC, isr_temp2		;
	inc isr_temp2				;
	out PORTC, isr_temp2		;
	inc isr_temp2				;
	out PORTC, isr_temp2		;
	inc isr_temp2				;
	out PORTC, isr_temp2		;
	inc isr_temp2				;
	out PORTC, isr_temp2		;
	inc isr_temp2				;
	out PORTC, isr_temp2		;
	inc isr_temp2				;
	out PORTC, isr_temp2		;
	inc isr_temp2				;
	out PORTC, isr_temp2		;
	inc isr_temp2				;
	out PORTC, isr_temp2		;
	inc isr_temp2				;
	out PORTC, isr_temp2		;
	inc isr_temp2				;
	out PORTC, isr_temp2		;
	inc isr_temp2				;
	out PORTC, isr_temp2		;
	inc isr_temp2				;
	out PORTC, isr_temp2		;
	inc isr_temp2				;
	out PORTC, isr_temp2		;
	inc isr_temp2				;
	out PORTC, isr_temp2		;
	inc isr_temp2				;
	out PORTC, isr_temp2		;
	inc isr_temp2				;
	out PORTC, isr_temp2		;
	inc isr_temp2				;
	out PORTC, isr_temp2		;
	inc isr_temp2				;
	out PORTC, isr_temp2		;
	inc isr_temp2				;
	out PORTC, isr_temp2		;
	inc isr_temp2				;
	out PORTC, isr_temp2		;
	inc isr_temp2				;
	out PORTC, isr_temp2		;
	inc isr_temp2				;
	out PORTC, isr_temp2		;
	inc isr_temp2				;
	out PORTC, isr_temp2		;
	inc isr_temp2				;
	out PORTC, isr_temp2		;
	inc isr_temp2				;
	out PORTC, isr_temp2		;
	inc isr_temp2				;
	out PORTC, isr_temp2		;
	inc isr_temp2				;
	out PORTC, isr_temp2		;
	inc isr_temp2				;
	out PORTC, isr_temp2		;
	inc isr_temp2				;
	out PORTC, isr_temp2		;
	inc isr_temp2				;
	out PORTC, isr_temp2		;
	inc isr_temp2				;
	out PORTC, isr_temp2		;
	inc isr_temp2				;
	out PORTC, isr_temp2		;
	inc isr_temp2				;
	out PORTC, isr_temp2		;
	inc isr_temp2				;
	out PORTC, isr_temp2		;
	inc isr_temp2				;
	out PORTC, isr_temp2		;
	inc isr_temp2				;
	out PORTC, isr_temp2		;
	inc isr_temp2				;
	out PORTC, isr_temp2		;
	inc isr_temp2				;
	out PORTC, isr_temp2		;
	inc isr_temp2				;
	out PORTC, isr_temp2		;
	inc isr_temp2				;
	out PORTC, isr_temp2		;
	inc isr_temp2				;
	out PORTC, isr_temp2		;
	inc isr_temp2				;
	out PORTC, isr_temp2		;
	inc isr_temp2				;
	out PORTC, isr_temp2		;
	inc isr_temp2				;
	out PORTC, isr_temp2		;
	inc isr_temp2				;
	out PORTC, isr_temp2		;
	inc isr_temp2				;
	out PORTC, isr_temp2		;
	inc isr_temp2				;
	out PORTC, isr_temp2		;
	inc isr_temp2				;
	out PORTC, isr_temp2		;
	inc isr_temp2				;
	out PORTC, isr_temp2		;
	inc isr_temp2				;
	out PORTC, isr_temp2		;
	inc isr_temp2				;
	out PORTC, isr_temp2		;
	inc isr_temp2				;
	out PORTC, isr_temp2		;
	inc isr_temp2				;
	out PORTC, isr_temp2		;
	inc isr_temp2				;
	out PORTC, isr_temp2		;
	inc isr_temp2				;
	out PORTC, isr_temp2		;
	inc isr_temp2				;
	out PORTC, isr_temp2		;
	inc isr_temp2				;
	out PORTC, isr_temp2		;
	inc isr_temp2				;
	out PORTC, isr_temp2		;
	inc isr_temp2				;
	out PORTC, isr_temp2		;
	inc isr_temp2				;
	out PORTC, isr_temp2		;
	inc isr_temp2				;
	out PORTC, isr_temp2		;
	inc isr_temp2				;
	out PORTC, isr_temp2		;
	inc isr_temp2				;
	out PORTC, isr_temp2		;
	inc isr_temp2				;
	out PORTC, isr_temp2		;
	inc isr_temp2				;
	out PORTC, isr_temp2		;
	inc isr_temp2				;
	out PORTC, isr_temp2		;
	inc isr_temp2				;
	out PORTC, isr_temp2		;
	inc isr_temp2				;
	out PORTC, isr_temp2		;
	inc isr_temp2				;
	out PORTC, isr_temp2		;
	inc isr_temp2				;
	out PORTC, isr_temp2		;
	inc isr_temp2				;
	out PORTC, isr_temp2		;
	inc isr_temp2				;
	out PORTC, isr_temp2		;
	inc isr_temp2				;
	out PORTC, isr_temp2		;
	inc isr_temp2				;
	out PORTC, isr_temp2		;
	inc isr_temp2				;
	out PORTC, isr_temp2		;
	inc isr_temp2				;
	out PORTC, isr_temp2		;
	inc isr_temp2				;
	out PORTC, isr_temp2		;
	inc isr_temp2				;
	out PORTC, isr_temp2		;
	inc isr_temp2				;
	out PORTC, isr_temp2		;
	inc isr_temp2				;
	out PORTC, isr_temp2		;
	inc isr_temp2				;
	out PORTC, isr_temp2		;
	inc isr_temp2				;
	out PORTC, isr_temp2		;
	inc isr_temp2				;
	out PORTC, isr_temp2		;
	inc isr_temp2				;
	out PORTC, isr_temp2		;
	inc isr_temp2				;
	out PORTC, isr_temp2		;
	inc isr_temp2				;
	out PORTC, isr_temp2		;
	inc isr_temp2				;
	out PORTC, isr_temp2		;
	inc isr_temp2				;
	out PORTC, isr_temp2		;
	inc isr_temp2				;
	out PORTC, isr_temp2		;
	inc isr_temp2				;
	out PORTC, isr_temp2		;
	inc isr_temp2				;
	out PORTC, isr_temp2		;
	inc isr_temp2				;
	out PORTC, isr_temp2		;
	inc isr_temp2				;
	out PORTC, isr_temp2		;
	inc isr_temp2				;
	out PORTC, isr_temp2		;
	inc isr_temp2				;
	out PORTC, isr_temp2		;
	inc isr_temp2				;
	out PORTC, isr_temp2		;
	inc isr_temp2				;
	out PORTC, isr_temp2		;
	inc isr_temp2				;
	out PORTC, isr_temp2		;
	inc isr_temp2				;
	out PORTC, isr_temp2		;
	inc isr_temp2				;
	out PORTC, isr_temp2		;
	inc isr_temp2				;
	out PORTC, isr_temp2		;
	inc isr_temp2				;
	out PORTC, isr_temp2		;
	inc isr_temp2				;
	out PORTC, isr_temp2		;
	inc isr_temp2				;
	out PORTC, isr_temp2		;
	inc isr_temp2				;
	out PORTC, isr_temp2		;
	inc isr_temp2				;
	out PORTC, isr_temp2		;
	inc isr_temp2				;
	out PORTC, isr_temp2		;
	inc isr_temp2				;
	out PORTC, isr_temp2		;
	inc isr_temp2				;
	out PORTC, isr_temp2		;
	inc isr_temp2				;
	out PORTC, isr_temp2		;
	inc isr_temp2				;
	out PORTC, isr_temp2		;
	inc isr_temp2				;
	out PORTC, isr_temp2		;
	inc isr_temp2				;
	out PORTC, isr_temp2		;
	inc isr_temp2				;
	out PORTC, isr_temp2		;
	inc isr_temp2				;
	out PORTC, isr_temp2		;
	inc isr_temp2				;
	out PORTC, isr_temp2		;
	inc isr_temp2				;
	out PORTC, isr_temp2		;
	inc isr_temp2				;
	out PORTC, isr_temp2		;
	inc isr_temp2				;
	out PORTC, isr_temp2		;
	inc isr_temp2				;
	out PORTC, isr_temp2		;
	inc isr_temp2				;
	out PORTC, isr_temp2		;
	inc isr_temp2				;
	out PORTC, isr_temp2		;
	inc isr_temp2				;
	out PORTC, isr_temp2		;
	inc isr_temp2				;
	out PORTC, isr_temp2		;
	inc isr_temp2				;
	out PORTC, isr_temp2		;
	inc isr_temp2				;
	out PORTC, isr_temp2		;
	inc isr_temp2				;
	out PORTC, isr_temp2		;
	inc isr_temp2				;
	out PORTC, isr_temp2		;
	inc isr_temp2				;
	out PORTC, isr_temp2		;
	inc isr_temp2				;
	out PORTC, isr_temp2		;
	inc isr_temp2				;
	out PORTC, isr_temp2		;
	inc isr_temp2				;
	out PORTC, isr_temp2		;
	inc isr_temp2				;
	out PORTC, isr_temp2		;
	inc isr_temp2				;
	out PORTC, isr_temp2		;
	inc isr_temp2				;
	out PORTC, isr_temp2		;
	inc isr_temp2				;
	out PORTC, isr_temp2		;
	inc isr_temp2				;
	out PORTC, isr_temp2		;
	inc isr_temp2				;
	out PORTC, isr_temp2		;
	inc isr_temp2				;
	out PORTC, isr_temp2		;
	inc isr_temp2				;
	out PORTC, isr_temp2		;
	inc isr_temp2				;
	out PORTC, isr_temp2		;
	inc isr_temp2				;
	out PORTC, isr_temp2		;
	inc isr_temp2				;
	out PORTC, isr_temp2		;
	inc isr_temp2				;
	out PORTC, isr_temp2		;
	inc isr_temp2				;
	out PORTC, isr_temp2		;
	inc isr_temp2				;
	out PORTC, isr_temp2		;
	inc isr_temp2				;
	out PORTC, isr_temp2		;
	inc isr_temp2				;
	out PORTC, isr_temp2		;
	inc isr_temp2				;
	out PORTC, isr_temp2		;
	inc isr_temp2				;
	out PORTC, isr_temp2		;
	inc isr_temp2				;
	out PORTC, isr_temp2		;
	inc isr_temp2				;
	out PORTC, isr_temp2		;
	inc isr_temp2				;
	out PORTC, isr_temp2		;
	inc isr_temp2				;
	out PORTC, isr_temp2		;
	inc isr_temp2				;
	out PORTC, isr_temp2		;
	inc isr_temp2				;
	out PORTC, isr_temp2		;
	inc isr_temp2				;
	out PORTC, isr_temp2		;
	inc isr_temp2				;
	out PORTC, isr_temp2		;
	inc isr_temp2				;
	out PORTC, isr_temp2		;
	inc isr_temp2				;
	out PORTC, isr_temp2		;
	inc isr_temp2				;
	out PORTC, isr_temp2		;
	inc isr_temp2				;
	out PORTC, isr_temp2		;
	inc isr_temp2				;
	out PORTC, isr_temp2		;
	inc isr_temp2				;
	out PORTC, isr_temp2		;
	inc isr_temp2				;
	out PORTC, isr_temp2		;
	inc isr_temp2				;
	out PORTC, isr_temp2		;
	inc isr_temp2				;
	out PORTC, isr_temp2		;
	inc isr_temp2				;
	out PORTC, isr_temp2		;
	inc isr_temp2				;
	out PORTC, isr_temp2		;
	inc isr_temp2				;
	out PORTC, isr_temp2		;
	inc isr_temp2				;
	out PORTC, isr_temp2		;
	inc isr_temp2				;
	out PORTC, isr_temp2		;
	inc isr_temp2				;
	out PORTC, isr_temp2		;
	inc isr_temp2				;
	out PORTC, isr_temp2		;
	inc isr_temp2				;
	out PORTC, isr_temp2		;
	inc isr_temp2				;
	out PORTC, isr_temp2		;
	inc isr_temp2				;
	out PORTC, isr_temp2		;
	inc isr_temp2				;
	out PORTC, isr_temp2		;
	inc isr_temp2				;
	out PORTC, isr_temp2		;
	inc isr_temp2				;
	out PORTC, isr_temp2		;
	inc isr_temp2				;
	out PORTC, isr_temp2		;
	inc isr_temp2				;
	out PORTC, isr_temp2		;
	inc isr_temp2				;
	out PORTC, isr_temp2		;
	inc isr_temp2				;
	out PORTC, isr_temp2		;
	inc isr_temp2				;
	out PORTC, isr_temp2		;
	inc isr_temp2				;
	out PORTC, isr_temp2		;
	inc isr_temp2				;
	out PORTC, isr_temp2		;
	inc isr_temp2				;
	out PORTC, isr_temp2		;
	inc isr_temp2				;
	out PORTC, isr_temp2		;
	inc isr_temp2				;
	out PORTC, isr_temp2		;
	inc isr_temp2				;
	out PORTC, isr_temp2		;
	inc isr_temp2				;
	out PORTC, isr_temp2		;
	inc isr_temp2				;
	out PORTC, isr_temp2		;
	inc isr_temp2				;
	out PORTC, isr_temp2		;
	inc isr_temp2				;
	out PORTC, isr_temp2		;
	inc isr_temp2				;
	out PORTC, isr_temp2		;
	inc isr_temp2				;
	out PORTC, isr_temp2		;
	inc isr_temp2				;
	out PORTC, isr_temp2		;
	inc isr_temp2				;
	out PORTC, isr_temp2		;
	inc isr_temp2				;
	out PORTC, isr_temp2		;
	inc isr_temp2				;
	out PORTC, isr_temp2		;
	inc isr_temp2				;
	out PORTC, isr_temp2		;
	inc isr_temp2				;
	out PORTC, isr_temp2		;
	inc isr_temp2				;
	out PORTC, isr_temp2		;
	inc isr_temp2				;
	out PORTC, isr_temp2		;
	inc isr_temp2				;
	out PORTC, isr_temp2		;
	inc isr_temp2				;
	out PORTC, isr_temp2		;
	inc isr_temp2				;
	out PORTC, isr_temp2		;
	inc isr_temp2				;
	out PORTC, isr_temp2		;
.endmacro
